### ISSUE TITLE
The left area is unable to recognize.

### ISSUE THREAD

**Issue by RayPS** [dclelland/DirectedPanGestureRecognizer#3]
I found the exactly same problem in the demo project, i think this is a bug?
![2017-06-25 21_08_39](https://user-images.githubusercontent.com/1941540/27516343-c9bcde86-59ea-11e7-909e-bf097a935d4d.gif)

**Comment by dclelland** [comment]
That sure is weird. I'll take a look at this when I get some spare time.

**Comment by dclelland** [comment]
Hey buddy, sorry to leave this for so long, had a busy couple of months! Are you still experiencing this issue? I'm only getting it on the simulator, not on my device.

**Comment by dclelland** [comment]
Have figured it out and pushed up a [fix](https://github.com/dclelland/DirectedPanGestureRecognizer/commit/2603353246e362299607d604bc2d2d062069420a#diff-d4fd51aaa0056779cff2a105a99b476e).
